### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by joezed** [joezed/Software-Design-Imp#2]
(assign to Paul)

**Comment by paulhavelin** [comment]
@pedrombmachado Feedback Required on USECASE2.png (in /doc folder)

**Comment by pedrombmachado** [comment]
Hi @joezed ,
   I believe you need at least one more type of user, namely the staff. You may want to have different levels of staff (e.g. line manager, supervisor and technician). 
I am not sure that it should be the Admin to assign staff rather than assigning a flight to a terminal queue with all the jobs assigned to that terminal. In this case the staff assigned to that terminal just has to check the next job in the queue. Everything else looks good.

**Comment by paulhavelin** [comment]
@pedrombmachado  hi Pedro, ive made these changes, ive added it to the repository if you could check its ok

[/doc -> 2.Requirements -> USECASE3.png]

**Comment by pedrombmachado** [comment]
Hi @paulhavelin ,
   I think the new version is covering all the evident steps.

**Comment by joezed** [comment]
This is done I think.
